### ISSUE TITLE
How long has the derotator being used

### ISSUE THREAD

**Issue by mrivas** [cytan299/field_derotator#2]
Hello cytan299.

Congratulations for you field de-rotator. May I ask if you have studied how long it can be used without producing significant distortions in the images?

Thanks,
Marcelo

**Comment by cytan299** [comment]
Experimentally, at least 8 minutes. But this depends on where the telescope is pointing. I intend to take 10 min frames to get a shot of M81. Unfortunately, not many clear nights around here.
