### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by scottwis** [cytan299/field_derotator#5]
Would you consider releasing this under a more permissive license than GPL 3? For example MIT or X11?

I use the The Sky-X Professional to control my imaging setup. That’s mostly because I have a Mac laptop and it’s one of the few things that works on the Mac.

In any case, it has the ability to control  mounts and field rotators, but not support for auto de-rotation as the mount moves.

However, it does  offer a JavaScript scripting interface that has access to both the mount and the rotator. 

So, my plan is to take your source, extract the parts for communicating rotational deltas, convert it to JavaScript, and then run it inside TheSkyX pro.

I can make the JS open source, but the plugins in TSX for communicating with the mount and the rotator are not open source.

Thus, if I did that it could be construed as “making a derivative work” and then “linking it with non free software”.

That would be incompatible with the GPL.

However If you were willing to do MIT or something similar, this would not be an issue.

**Comment by cytan299** [comment]
Hi Scott,
   I don't understand why a JS code that sits between the rotator and TheSkyX would violate GPL3.
   
  I would like to leave the license as GPL3 but I'm willing to consider adding an MIT license. However, I'm not familiar with relicensing. Do you have a link to how to do this properly?

cytan

**Comment by scottwis** [comment]
If all the contributors came from you, then you can just change the license file to the MIT version and you are good.

After some experiments with TSX, however, I don’t think I actually need you to re-license this.

TSX runs all it’s Java Script on its UI thread and it doesn’t expose anything related to the event loop (no setTimeout or process.nextTick()), so it’s not really amenable to long lived processes. If I write the whole thing in JavaScript it will make the rest of TSX unusable.

What it does support well, however, is communicating over TCP and executing small  scripts to exchange data.

For that case, I can just hack up your code and release my hacks as GPL and I am good (because the non free TSX code is just communicating with the GPL code over a socket), and that’s ok.

So, feel free to close this. Sorry to bug you.

**Comment by cytan299** [comment]
Hi Scott,
   Not a problem at all. Actually it is quite flattering to know that you're interested in my code :)

cytan
